version: '3'

networks:
  app-tier:
    driver: bridge

services:
  mysql-57:
    container_name: mysql-57
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/mysql-57/Dockerfile
    networks:
      app-tier:
        aliases:
          - mysql-57
    ports:
      - 3357:3306
    volumes:
      - ./mysql-data-57:/bitnami/mysql/data
  
  mysql-80:
    container_name: mysql-80
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/mysql-80/Dockerfile
    networks:
      app-tier:
        aliases:
          - mysql-80
    ports:
      - 3380:3306
    volumes:
      - ./mysql-data-80:/binami/mysql/data

  php-fpm-56:
    container_name: php-fpm-56
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/php-fpm-56/Dockerfile
    networks:
      app-tier:
        aliases:
          - php-fpm-56
    ports:
      - 9056:9000
    volumes:
      - ./vhosts:/var/www/vhosts
    depends_on:
      - mysql-57
  
  php-fpm-71:
    container_name: php-fpm-71
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/php-fpm-71/Dockerfile
    networks:
      app-tier:
        aliases:
          - php-fpm-71
    ports:
      - 9071:9000
    volumes:
      - ./vhosts:/var/www/vhosts
    depends_on:
      - mysql-57
      - mysql-80
  
  php-fpm-72:
    container_name: php-fpm-72
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/php-fpm-72/Dockerfile
    networks:
      app-tier:
        aliases:
          - php-fpm-72
    ports:
      - 9072:9000
    volumes:
      - ./vhosts:/var/www/vhosts
    depends_on:
      - mysql-57
      - mysql-80
  
  php-fpm-73:
    container_name: php-fpm-73
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/php-fpm-73/Dockerfile
    networks:
      app-tier:
        aliases:
          - php-fpm-73
    ports:
      - 9073:9000
    volumes:
      - ./vhosts:/var/www/vhosts
    depends_on:
      - mysql-57
      - mysql-80
  
  apache:
    container_name: apache
    build:
      context: .
      dockerfile: .docker/apache/Dockerfile
    depends_on:
      - php-fpm-56
      - php-fpm-71
      - php-fpm-72
      - php-fpm-73
    networks:
      app-tier:
        aliases:
          - apache
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - .docker/apache/conf/httpd.conf:/bitnami/apache/conf/httpd.conf
      - .docker/apache/conf/macro.conf:/bitnami/apache/conf/macro.conf
      - .docker/apache/conf/vhosts:/bitnami/apache/conf/vhosts-dev
      - ./vhosts:/var/www/vhosts
