version: '3'

networks:
  app-tier:
    driver: bridge

services:

  mysql-55:
    container_name: mysql-55
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/mysql-55/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    networks:
      app-tier:
        aliases:
          - mysql-55
    ports:
      - 3355:3306
    volumes:
      - ./data/mysql-55:/var/lib/mysql

  mysql-56:
    container_name: mysql-56
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/mysql-56/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    networks:
      app-tier:
        aliases:
          - mysql-56
    ports:
      - 3356:3306
    volumes:
      - ./data/mysql-56:/var/lib/mysql

  mysql-57:
    container_name: mysql-57
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/mysql-57/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    networks:
      app-tier:
        aliases:
          - mysql-57
    ports:
      - 3357:3306
    volumes:
      - ./data/mysql-57:/var/lib/mysql

  mysql-80:
    container_name: mysql-80
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/mysql-80/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    networks:
      app-tier:
        aliases:
          - mysql-80
    ports:
      - 3380:3306
    volumes:
      - ./data/mysql-80:/var/lib/mysql

  percona-56:
    container_name: percona-56
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/percona-56/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    networks:
      app-tier:
        aliases:
          - percona-56
    ports:
      - 3456:3306
    volumes:
      - ./data/percona-56:/var/lib/mysql

  percona-57:
    container_name: percona-57
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/percona-57/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    networks:
      app-tier:
        aliases:
          - percona-57
    ports:
      - 3457:3306
    volumes:
      - ./data/percona-57:/var/lib/mysql

  percona-80:
    container_name: percona-80
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/percona-80/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    networks:
      app-tier:
        aliases:
          - percona-80
    ports:
      - 3480:3306
    volumes:
      - ./data/percona-80:/var/lib/mysql

  mariadb-55:
    container_name: mariadb-55
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/mariadb-55/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    networks:
      app-tier:
        aliases:
          - mariadb-55
    ports:
      - 3555:3306
    volumes:
      - ./data/mariadb-55:/var/lib/mysql

  mariadb-100:
    container_name: mariadb-100
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/mariadb-100/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    networks:
      app-tier:
        aliases:
          - mariadb-100
    ports:
      - 3500:3306
    volumes:
      - ./data/mariadb-100:/var/lib/mysql

  mariadb-101:
    container_name: mariadb-101
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/mariadb-101/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    networks:
      app-tier:
        aliases:
          - mariadb-101
    ports:
      - 3501:3306
    volumes:
      - ./data/mariadb-101:/var/lib/mysql

  mariadb-102:
    container_name: mariadb-102
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/mariadb-102/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    networks:
      app-tier:
        aliases:
          - mariadb-102
    ports:
      - 3502:3306
    volumes:
      - ./data/mariadb-102:/var/lib/mysql

  mariadb-103:
    container_name: mariadb-103
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/mariadb-103/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    networks:
      app-tier:
        aliases:
          - mariadb-103
    ports:
      - 3503:3306
    volumes:
      - ./data/mariadb-103:/var/lib/mysql

  mariadb-104:
    container_name: mariadb-104
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/mariadb-104/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    networks:
      app-tier:
        aliases:
          - mariadb-104
    ports:
      - 3504:3306
    volumes:
      - ./data/mariadb-104:/var/lib/mysql

  php-fpm-56:
    container_name: php-fpm-56
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/php-fpm-56/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - DISABLED_PHP_FPM_MODULES=${DISABLED_PHP_FPM_MODULES}
    networks:
      app-tier:
        aliases:
          - php-fpm-56
    ports:
      - 9056:9000
    volumes:
      - ./vhosts:/var/www/vhosts
      - .docker/php-fpm-56/etc/php.ini:/opt/docker/etc/php/php.ini

  php-fpm-70:
    container_name: php-fpm-70
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/php-fpm-70/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - DISABLED_PHP_FPM_MODULES=${DISABLED_PHP_FPM_MODULES}
    networks:
      app-tier:
        aliases:
          - php-fpm-70
    ports:
      - 9070:9000
    volumes:
      - ./vhosts:/var/www/vhosts
      - .docker/php-fpm-70/etc/php.ini:/opt/docker/etc/php/php.ini

  php-fpm-71:
    container_name: php-fpm-71
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/php-fpm-71/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - DISABLED_PHP_FPM_MODULES=${DISABLED_PHP_FPM_MODULES}
    networks:
      app-tier:
        aliases:
          - php-fpm-71
    ports:
      - 9071:9000
    volumes:
      - ./vhosts:/var/www/vhosts
      - .docker/php-fpm-71/etc/php.ini:/opt/docker/etc/php/php.ini

  php-fpm-72:
    container_name: php-fpm-72
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/php-fpm-72/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - DISABLED_PHP_FPM_MODULES=${DISABLED_PHP_FPM_MODULES}
    networks:
      app-tier:
        aliases:
          - php-fpm-72
    ports:
      - 9072:9000
    volumes:
      - ./vhosts:/var/www/vhosts
      - .docker/php-fpm-72/etc/php.ini:/opt/docker/etc/php/php.ini

  php-fpm-73:
    container_name: php-fpm-73
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/php-fpm-73/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - DISABLED_PHP_FPM_MODULES=${DISABLED_PHP_FPM_MODULES}
    networks:
      app-tier:
        aliases:
          - php-fpm-73
    ports:
      - 9073:9000
    volumes:
      - ./vhosts:/var/www/vhosts
      - .docker/php-fpm-73/etc/conf.d:/php.ini:/opt/docker/etc/php/php.ini

  php-cli-56:
    container_name: php-cli-56
    env_file: .docker.env
    environment:
      - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
    build:
      context: .
      dockerfile: .docker/php-cli-56/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - DISABLED_PHP_CLI_MODULES=${DISABLED_PHP_CLI_MODULES}
    networks:
      app-tier:
        aliases:
          - php-cli-56
    volumes:
      - ./vhosts:/var/www/vhosts
      - .docker/php-cli-56/etc/php.ini:/opt/docker/etc/php/php.ini
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK

  php-cli-70:
    container_name: php-cli-70
    env_file: .docker.env
    environment:
      - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
    build:
      context: .
      dockerfile: .docker/php-cli-70/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - DISABLED_PHP_CLI_MODULES=${DISABLED_PHP_CLI_MODULES}
    networks:
      app-tier:
        aliases:
          - php-cli-70
    volumes:
      - ./vhosts:/var/www/vhosts
      - .docker/php-cli-70/etc/php.ini:/opt/docker/etc/php/php.ini
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK

  php-cli-71:
    container_name: php-cli-71
    env_file: .docker.env
    environment:
      - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
    build:
      context: .
      dockerfile: .docker/php-cli-71/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - DISABLED_PHP_CLI_MODULES=${DISABLED_PHP_CLI_MODULES}
    networks:
      app-tier:
        aliases:
          - php-cli-71
    volumes:
      - ./vhosts:/var/www/vhosts
      - .docker/php-cli-71/etc/php.ini:/opt/docker/etc/php/php.ini
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK

  php-cli-72:
    container_name: php-cli-72
    env_file: .docker.env
    environment:
      - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
    build:
      context: .
      dockerfile: .docker/php-cli-72/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - DISABLED_PHP_CLI_MODULES=${DISABLED_PHP_CLI_MODULES}
    networks:
      app-tier:
        aliases:
          - php-cli-72
    volumes:
      - ./vhosts:/var/www/vhosts
      - .docker/php-cli-72/etc/php.ini:/opt/docker/etc/php/php.ini
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK

  php-cli-73:
    container_name: php-cli-73
    env_file: .docker.env
    environment:
      - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
    build:
      context: .
      dockerfile: .docker/php-cli-73/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - DISABLED_PHP_CLI_MODULES=${DISABLED_PHP_CLI_MODULES}
    networks:
      app-tier:
        aliases:
          - php-cli-73
    volumes:
      - ./vhosts:/var/www/vhosts
      - .docker/php-cli-73/etc/php.ini:/opt/docker/etc/php/php.ini
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK

  solr-771:
    container_name: solr-771
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/solr-771/Dockerfile
    networks:
      app-tier:
        aliases:
          - solr-771
    ports:
      - 8983:8983
    volumes:
      - ./vhosts:/var/www/vhosts
      - ./data/solr-771:/bitnami/solr/data
      - ./solr-771-lib:/var/www/solr/lib

  tomcat-9:
    container_name: tomcat-9
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/tomcat-9/Dockerfile
    networks:
      app-tier:
        aliases:
          - tomcat-9
    ports:
      - 8888:8080
    volumes:
      - ./data/tomcat-9:/bitnami
      - ./vhosts:/var/www/vhosts

  apache:
    container_name: apache
    build:
      context: .
      dockerfile: .docker/apache/Dockerfile
    networks:
      app-tier:
        aliases:
          - apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - .docker/apache/conf/conf.d:/opt/docker/etc/httpd/conf.d
      - .docker/apache/conf/vhost.common.d:/opt/docker/etc/httpd/vhost.common.d
      - .docker/apache/app:/app
      - ./vhosts:/var/www/vhosts

